### ISSUE TITLE
Add forgot password feature

### ISSUE THREAD

**Issue by thakurthegr8** [thakurthegr8/loop#4]
Make sure you followed code guidelines

**Comment by hemanth110702** [comment]
Hey, I would like to work on this. Can you please assign this to me?

**Comment by hemanth110702** [comment]
Dear @thakurthegr8,

I regret to inform you that I am facing difficulties in proceeding with the assigned task. While attempting to initialize the repository, I have encountered persistent errors, hindering my progress. I apologize for any inconvenience this has caused and any time that may have been wasted.

If it is possible, I would greatly appreciate your guidance in resolving the issues related to repository initialization. However, I understand that this may require additional time and effort on your part. If it would be more convenient, please feel free to unassign me from this particular task.

I am sincerely sorry for any disruption, and I remain committed to contributing to the project in any other capacity or on different tasks if possible. Thank you for your understanding and support.

Best regards,
@hemanth110702

**Comment by thakurthegr8** [comment]
Which issues are you currently facing? @hemanth110702

**Comment by hemanth110702** [comment]
I am **glad** and **grateful** for your consideration @thakurthegr8
- Previously I got so many errors in my console at the time of initilization, but trying it for a long time now it is working.
- Just now the issue was resolved.
- Now I will immedieately work on my task.

*Thank you very much*

**Comment by thakurthegr8** [comment]
Great lmk anything you need @hemanth110702
